#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Fixing Prettier standards

npm run format 
# Checking ESLint Standards
npm run check-lint ||
(
        echo '😤 Get that weak code out of here! 😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Checking tsconfig standards
npm run check-types ||
(
    echo '❌🤡 Failed Type check. ❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... we can try to build
echo '🤔... Alright... Code looks good to me... Trying to build now. 🤔'

npm run build ||
(
    echo '❌👷 Better call Bob... Because your build failed ❌👷
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
